version: "3.9"
services:
  db:
    image: mysql:8.0.28
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bookstore
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  app:
    build: ./app
    container_name: flask-app
    links:
      - db
    ports:
      - "5000:5000"